# Project Details

[project]
name = "python-template"
version = "0.0.1"
description = "Base template for Python projects"
authors = [
    {name = "Your Name", email = "email@example.com"},
]
requires-python = ">=3.10"
license = {file = "LICENSE"}
